config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/about'

  resources :dogs
  resources :owners

  root 'pages#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :dogs
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :owner
  belongs_to :breed

  validates :name, :owner_id, presence: true

  has_attached_file :avatar, :styles => {
                    :medium => "300x300>",
                    :thumb => "75x75>" },
                    :default_url => ":style_missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # validates_attachment_size :avatar, :less_than => 33.megabytes
  #   :unless => Proc.new {|m| m[:avatar_file_name].blank?}
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :dogs


  def last_first
    "#{last_name}, #{first_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    if params[:search]
      @dogs = Dog.where("name LIKE '%#{params[:search]}%'")
      if @dogs.size.zero?
        flash[:notice] = "No results found for \"#{params[:search]}\"."
        # flash[:notice] = "No results found for #{params[:search]}."
      end
    else
      @dogs = Dog.all
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)
    @dogs = Dog.all

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.js {}
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.js { render :action => "new" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    @dogs = Dog.all

    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to dogs_path, notice: 'Dog was successfully updated.' }
        format.js {}
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.js { render :action => "edit" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dogs = Dog.all
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :owner_id, :breed_id, :dob, :vet, :vet_phone,
                                  :in_daycare, :dietary_restrictions, :avatar)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :phone, :emerg_name, :emerg_phone)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dogs/_dog.html.erb
<div class="col-md-3">
 <div class="panel panel-default <%= 'panel-success' if dog.in_daycare %>">
   <div class="panel-heading">
     <h3 class="panel-title"><%= dog.name %> <%= dog.owner.last_name %></h3>
   </div>
   <div class="panel-body">
    <a href="#" data-toggle="modal" data-target="#show_dog_<%= dog.id %>">
     <%= image_tag dog.avatar.url(:medium), class: "img-responsive" %>
    </a>
   </div>
   <div class="panel-footer">

     In Daycare? <%= dog.in_daycare ? 'Yes':'No' %>
     <br>

     <%= link_to dog do %>
      <%= fa_icon 'eye'%>
        <% end %>

     <%= link_to edit_dog_path(dog), remote: true  do %>
        <%= fa_icon 'pencil' %>
     <% end %>

     <%= link_to dog, remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%= fa_icon 'trash-o' %>
     <% end %>

     <%= form_for(dog, url: dog_path(dog), remote: true, :html => {class: "form-inline"}) do |f| %>
      <% if dog.in_daycare %>
        <%= f.hidden_field :in_daycare, :value => false %>
        <%= f.submit "Check-out", class: "btn btn-danger btn-xs" %>
      <% else %>
         <%= f.hidden_field :in_daycare, :value => true %>
         <%= f.submit "Check in", class: "btn btn-primary btn-xs" %>
      <% end %>
    <% end %>
   </div>
 </div> <!-- panel -->
</div> <!-- col -->

<!-- Modal -->
<div class="modal fade" id="show_dog_<%= dog.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel"><%= dog.name %> <%= dog.owner.last_name %></h3>
      </div>
      <div class="modal-body">

        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-4"><%= image_tag dog.avatar.url(:medium), class: "img-responsive" %></div>
            <div class="col-sm-8">


              <p><strong> Name: </strong> <%= dog.name %></p>
              <p><strong> Owner: </strong> <%= "#{dog.owner.first_name} #{dog.owner.last_name}" %></p>
              <p><strong> Breed: </strong> <%= dog.breed.breed %></p>
              <p><strong> Dob: </strong> <%= dog.dob.stamp_like('January 1, 2015') %></p>
              <p><strong> Vet: </strong> <%= dog.vet %></p>
              <p><strong> Vet phone: </strong> <%= dog.vet_phone %></p>
              <p><strong> In daycare: </strong> <%= dog.in_daycare %></p>
              <p><strong>Dietary restrictions: </strong> <%= dog.dietary_restrictions %></p>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dogs/_form.html.erb
<div class="modal-body">
  <%= form_for(@dog, remote: true) do |f| %>
    <% if @dog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

        <ul>
        <% @dog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :owner_id %><br>
      <%= f.collection_select :owner_id, Owner.all,
                              :id, :last_first, {prompt: "Select an owner"},
                              class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :breed_id %><br>
      <%= f.collection_select :breed_id, Breed.all,
                              :id, :breed, {prompt: "Select a breed"},
                              class: "form-control" %>
    </div>
    <div class="field">
     <%# TODO: add a datepicker gem and make this a cool datepicker. %>
      <%= f.label :dob %><br>
      <%= f.date_select :dob %>
    </div>
    <div class="field">
      <%= f.label :vet %><br>
      <%= f.text_field :vet %>
    </div>
    <div class="field">
      <%= f.label :vet_phone %><br>
      <%= f.text_field :vet_phone %>
    </div>
    <div class="field">
      <%= f.label :in_daycare %><br>
      <%= f.check_box :in_daycare %>
    </div>
    <div class="field">
      <%= f.label :dietary_restrictions %><br>
      <%= f.text_field :dietary_restrictions %>
    </div>
    <div class="field">
     <%= f.label :avatar %><br>
     <%= f.file_field :avatar %>
    </div>

    <div class="actions modal-footer">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/dogs/create.js.erb
//Re-render
$('#dogs').html("<%= j (render @dogs) %>");

$('#dog_form_modal').modal('hide');

app/views/dogs/destroy.js.erb
$('#dogs').html("<%= j (render @dogs) %>");

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/edit.js.erb
// Render dog form
$('#dog-form').html("<%= j (render 'form') %>");
$('#dog-form').show();

// Show the modal
$('#dog_form_modal').modal('show');

app/views/dogs/index.html.erb
<br>

<h1>Listing Dogs</h1>
<p>
<%= link_to 'New Dog', new_dog_path, class: "btn btn-default btn-xs", remote: true %>
<!-- <div id="dog-form">
</div> -->
</p>

<br>
<br>

  <div class="row">

    <div id="dogs">
      <%= render @dogs %>
    </div>

  </div> <!-- row -->
<br>
<!-- Modal -->
<div class="modal fade" id="dog_form_modal" tabindex="-1" role="dialog" aria-labelledby="dogFormModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Dog Details</h3>
      </div>
      <div id="dog-form"></div>

    </div>
  </div>
</div>


<%= link_to 'New Dog', new_dog_path, class: "btn btn-default btn-xs" %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/new.js.erb
// Render dog form
$('#dog-form').html("<%= j (render 'form') %>");
$('#dog-form').show();

// Show the modal
$('#dog_form_modal').modal('show');

app/views/dogs/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<br>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= "#{@dog.owner.first_name} #{@dog.owner.last_name}" %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed.breed %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @dog.dob.stamp_like('January 1, 2015') %>
</p>

<p>
  <strong>Vet:</strong>
  <%= @dog.vet %>
</p>

<p>
  <strong>Vet phone:</strong>
  <%= @dog.vet_phone %>
</p>

<p>
  <strong>In daycare:</strong>
  <%= @dog.in_daycare %>
</p>

<p>
  <strong>Dietary restrictions:</strong>
  <%= @dog.dietary_restrictions %>
</p>
<p>
<%= image_tag @dog.avatar.url %>
</p>
<p>
<%= image_tag @dog.avatar.url(:medium) %>
</p>
<p>
<%= image_tag @dog.avatar.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/update.js.erb
//Re-render
$('#dogs').html("<%= j (render @dogs) %>");

$('#dog_form_modal').modal('hide');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>DoggyDallas</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.3.5/yeti/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Owners", owners_url %></li>
        <li><%= link_to "Dogs", dogs_url %></li>
        <li><%= link_to "About", pages_about_url %></li>
      </ul>

      <%= form_tag("/dogs", method: "get", role: "search", class: "navbar-form navbar-right") do %>
        <div class="form-group">
          <%= text_field_tag(:search, nil, placeholder: "Fido", class: "form-control input-xs") %>
        </div>
          <%= submit_tag("Search", class: "btn btn-default btn btn-xs") %>
      <% end %>




    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :emerg_name %><br>
    <%= f.text_field :emerg_name %>
  </div>
  <div class="field">
    <%= f.label :emerg_phone %><br>
    <%= f.text_field :emerg_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing Owners</h1>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Emerg name</th>
      <th>Emerg phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= owner.phone %></td>
        <td><%= owner.emerg_name %></td>
        <td><%= owner.emerg_phone %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<br>

<p>
  <strong>First name:</strong>
  <%= @owner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @owner.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @owner.phone %>
</p>

<p>
  <strong>Emerg name:</strong>
  <%= @owner.emerg_name %>
</p>

<p>
  <strong>Emerg phone:</strong>
  <%= @owner.emerg_phone %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
</div>
<div class="jumbotron">
  <h1>Big-D Dogs!</h1>
  <p>Where all the cool dogs come to hang out with their friends!</p>
</div>